services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  aggregator:
    restart: always
    image: aggregator:alpha6
    network_mode: host
    build:
      context: .
      dockerfile: ./aggregator/aggregator.Dockerfile

  proxy:
    restart: always
    ports:
      - 8080:8080
    image: proxy:alpha7
    network_mode: host
    build:
      context: .
      dockerfile: ./proxy/proxy.Dockerfile

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local